### ISSUE TITLE
flag provided but not defined: -coverpkg

### ISSUE THREAD

**Issue by AlekSi** [pierrre/gotestcover#8]
I'm trying to run `gotestcover -v -coverprofile cover.out -coverpkg $(shell go list ./... | grep -v vendor/ | paste -s -d, -) $(shell go list ./... | grep -v vendor/)`.

Also, it would be nice if `gotestcover` was able to:
1) omit `vendor/`;
2) optionally populate the value of `-coverpkg` automatically.

**Comment by pierrre** [comment]
Here is how `gotestcover` works:
- take packages in arguments and resolve them with `go list`
- for each package, run `go test -cover -coverprofile cover.out` (+ forward all supported flags, see https://github.com/pierrre/gotestcover/blob/master/gotestcover.go#L74-L87)
- merge all cover profiles and write to a file

> 2) optionally populate the value of -coverpkg automatically.

I deliberately ignored the flag `-coverpkg`, because I don't think it will work well with `gotestcover`.
How should it forward `-coverpkg` each time it runs `go test -cover`?

> 1) omit vendor/;

`gotestcover` is a simple wrapper around `go test -cover` that helps to merge cover profiles.
It will always follow the same rules as `go test`.
If `go test` adds a flag to ignore `vendor`, I will add it.

**Comment by AlekSi** [comment]
> take packages in arguments and resolve them with `go list`

After that step, you have the full list of packages.

> How should it forward `-coverpkg` each time it runs `go test -cover`?

If `gotestcover` is run with flag `-foo`, add `-coverpkg` to `go test` invocation with the value of the list of packages from the first step.

> `gotestcover` is a simple wrapper around `go test -cover` that helps to merge cover profiles.
> It will always follow the same rules as go test.

I mean omit `vendor/` from the result of `go list`. Basically, `go list` does not return valid import paths for vendored dependencies. See https://github.com/golang/go/issues/11659 for details.

**Comment by powerman** [comment]
If I force gotestcover to run `go test` with `-coverpkg ./...` then it incorrectly merge cover profiles - looks like it take last result for each package instead of actually merging them.

For example, if tests for package A has covered lines 10-20 in package C, and tests for package B has covered lines 30-40 in package C, then merged result will show only either lines 10-20 or lines 30-40 as covered in package C.

Is there easy way to fix this? Because using `-coverpkg ./...` looks natural use case for gotestcover.

**Comment by pierrre** [comment]
Please read https://github.com/pierrre/gotestcover#deprecated

**Comment by powerman** [comment]
Non-deprecated fork with -coverpkg support is available at https://github.com/powerman/gotestcover
